### ISSUE TITLE
Anonymous function / Closures usage

### ISSUE THREAD

**Issue by DevinWalker** [CalderaWP/cf-connected-forms#2]
Hey Guys - really cool Add-on for Caldera Forms. I'm wondering? Why are you using anonymous functions (also called Closures) within your actions? There's downsides to this within plugins:
- can't use `remove_filter()`
- 5.3+ only
- usage of functions multiple times 

https://github.com/CalderaWP/cf-connected-forms/blob/master/includes/functions.php#L29
https://github.com/CalderaWP/cf-connected-forms/blob/master/includes/functions.php#L45
https://github.com/CalderaWP/cf-connected-forms/blob/master/includes/functions.php#L627

**Comment by Shelob9** [comment]
I think those closures make sense beacuse those filters should never be
removed and their callbacks shouldn't be  reused elsewhere. When not using
classes I think closures are excellent ways to get around these issues.

And yes, we should be following our normal pattern of only loading the
plugin if the user is on 5.3 or later to prevent errors. Good catch, I'll
fix that.

**Comment by Shelob9** [comment]
#3

**Comment by DavidCramer** [comment]
Exactly. Those 3 are fundamental to operation. Basically if you are wanting to remove action on any of those it would be better to disable the plugin.

**Comment by Shelob9** [comment]
Closed since ffc1612 doesn't allow loading on 5.2
