### ISSUE TITLE
Need to not load if PHP < PHP 5.2 

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/cf-connected-forms#3]
You know, like we do in all our other plugins.

**Comment by jamesgol** [comment]
I hope you mean not load if  <= 5.2 or only load if > 5.2.  I'm not sure how many people are using a PHP version less than 5.2 :)

Screw people using old versions of PHP, they all suck

**Comment by Shelob9** [comment]
oops :)

Throwing an admin nag when PHP bad is a great way to inform people, who probably don't know that their host is giving them a shit PHP version/ that's a concern. We should really throw admin nag on 5.4 and below. Well, really WordPress should, but that's a bag of worms.
