### ISSUE TITLE
Conditional Form automatically submitting

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-connected-forms#31]
Tested connected forms v1.08 with Caldera 1.4.8

The issue comes into play when you go back from an option you selected initially and then change your option. When changing your option it then automatically chooses the second option and submits the form without showing any form contents.

i.e.

Have a parent form with a toggle switch with two options, 'B' and 'C' and create a condition to redirect to form B or C respectively of the toggle switch selection.

1. Choose option C > go to form C > go back to parent form to change option
2. Choose option B > go to form b and automatically submits, do not see any content on this screen 

This happens if you reverse the process by choosing 'B' first and then choosing 'C' second.

**Comment by Shelob9** [comment]
This was beacuse of a database error, which is fixed thanks to 7d7ac63d6ba0ea389283a56f60e18bd596e2807a and https://github.com/CalderaWP/Caldera-Forms/commit/23357abd973ced7aa2a4d3aa846e98e5e8818dcb
