### ISSUE TITLE
Star Rating issue with connected forms

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-connected-forms#34]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.4.8

## What Is The Unexpected Behaviour?

Conditions Errors:
if [star rating field] is greater than X does not work with connected forms.  (Investigating if conditions with star rating works on single forms in 1.5.x)

if [star rating field] is X, this works and directs to the second form, however if you return back to the first form star ratings disappear entirely. No errors shown.

**Comment by Shelob9** [comment]
Related https://github.com/CalderaWP/Caldera-Forms/issues/1520

**Comment by Shelob9** [comment]
Close via edd15ab
