### ISSUE TITLE
Calculating between connected forms doesn't work

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-connected-forms#35]
Version: 1.4.8

Description: You are unable to calculate a total on form 1, pass it to form 2 and add additional calculations to this to get the total.

I.e. Total of form 1 passed to form 2 and add form 1 total to the total of form 2. Returns blank data.

Calculation fields may be passed through to fields but you are unable to add those fields together.

**Comment by Shelob9** [comment]
Closing as not supported, but easy work around is documented here: https://calderaforms.com/doc/sharing-data-connected-forms#connected-forms-calculations
