### ISSUE TITLE
Passing calculated totals within Caldera Forms not displaying on frontend

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-connected-forms#38]
You are now able to calculate totals across connected forms.

However, the total shown on the final form does not show on the frontend. The value in the entries is correct.

I.e. Form A price is 10, Form B price is 10 + price of form B = 20. This does not show on frontend and total shows blank but in entry it shows 20.

I hope this makes sense.

**Comment by Shelob9** [comment]
I toook another stab at this, decided to stand by the decision not so support it. Work aroung is described here: https://calderaforms.com/doc/sharing-data-connected-forms/#connected-forms-calculations
