### ISSUE TITLE
Back Button doesn't work and changes to a text field

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-connected-forms#39]
Back button on connected form doesn't work and it becomes a text field which you can change the text for.

Two back buttons are shown intermittently, sometimes only one back button is shown and turns into a text field.

The larger Back button turns into a text field when you click on it.

![connected-forms-back-button-error](https://cloud.githubusercontent.com/assets/12629136/23072499/912d64f6-f53a-11e6-96aa-f9757b17bb60.png)

![backend](https://cloud.githubusercontent.com/assets/12629136/23072534/b52cc130-f53a-11e6-9a7e-babc57d68c75.png)

**Comment by Shelob9** [comment]
Good catch @andrewlima I will make sure all buttons are removed

**Comment by Shelob9** [comment]
Close via	5cd500f
