### ISSUE TITLE
{prev:*} doesn't work correctly in Connected Forms 1.1 and 1.5 in HTML fields

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-connected-forms#41]
Form A has a name field.

Form B has an HTML field that says - 

`Hi {prev:first_name}, please select the submit button`

Output to the front end is the value of `{prev:first_name}` only, no other strings.

**Comment by Shelob9** [comment]
Should be fixed with Caldera Forms 1.5.0.1
