### ISSUE TITLE
Disabling Caldera Forms while Connected Forms still active throws PHP Notice

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-connected-forms#42]
When you disable Caldera Forms and have Connected Forms still installed and active, this warning appears - 

PHP Notice:  Use of undefined constant CFCORE_VER - assumed 'CFCORE_VER' in C:\Users\Andrew\Documents\Websites\caldera.dev\wp-content\plugins\cf-connected-forms\plugin.php on line 46

**Comment by Shelob9** [comment]
Close via 	a8c0215
