### ISSUE TITLE
Moving between forms multiple times submits data after the first process.

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-connected-forms#43]
If a user goes to the next form and back to the previous form when they click next to go back to the next form it submits the current form they are on.

No PHP or JS errors.

**Comment by andrewlimaza** [comment]
Example:
1. Enter required fields and press "next"
2. Press "back"
3. Press "next"
-> Form will not continue and just submit content from step1

**Comment by Shelob9** [comment]
So problem was that when you go back and then forward the processor that is added on demand didn't get run, so the $form[ 'connections' ] index wasn't populated with the next form ID and therefore it was interprutted as completed.

**Comment by Shelob9** [comment]
309a795 is a partial fix. This provides for succesful back/forward nav, but the entries are not always recorded properly.

**Comment by Shelob9** [comment]
Should be fixed via 		3053ddc
 and 	309a795
