### ISSUE TITLE
{Summary} shows results in reversed order for connected forms

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-connected-forms#49]
When using Connected Forms, the form results are shown in reverse order of form order.

Screenshot -

<img width="1089" alt="screen shot 2017-04-28 at 11 03 43 am" src="https://cloud.githubusercontent.com/assets/12629136/25522488/5e568a58-2c03-11e7-81f5-1d0a9ff4e764.png">

**Comment by Shelob9** [comment]
add_filter( 'caldera_forms_get_field_order', function( $order, $form ){
		//change to connected form ID
		if( 'CF1323' == $form[ 'ID' ] ){
			$order = array_reverse( $order );
		}
	
		return $order;
	});

**Comment by IowaBoy1** [comment]
How do I use this?  Will this be added to connected forms so it corrects this for all forms (without having to add every form ID that is created)?

**Comment by Shelob9** [comment]
Testing with Caldera Forms 1.5.0.10 I get them in the right order.

I am not using that workaround I suggested before, which would actually cause this. So @IowaBoy1 if you had that filter in place, remove it and try again.

![screenshot from 2017-05-29 14-16-42](https://cloud.githubusercontent.com/assets/1994311/26558895/fe3a0f16-4479-11e7-94a1-87595e1484e6.png)
