### ISSUE TITLE
Passing values from previous forms into calculation fields causing calculations to fail.

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-connected-forms#50]
Here is a scenario -

Form 1 - Calculate a subtotal of current form (i.e. qty X 10 = subtotal)
Form 2 - Pass subtotal into a text or hidden field. The default value of the text field that contains the default value of the subtotal on form 1. Use this text field in calculation and the front-end displays blank under the calculation. Refresh the form and the total appears.

Custom formula for Form 2 (with Form 1 subtotal example)

(%quantity_for_form_2% * 5) + %hidden_field_with_value_from_form_1%

**Comment by andrewlimaza** [comment]
Values in entries look correctly saved even when the front-end total on form 2 is blank.

**Comment by Shelob9** [comment]
Please retest with Caldera Forms 1.5.0.9 ? Should be fixed via https://github.com/CalderaWP/Caldera-Forms/issues/1484

**Comment by Shelob9** [comment]
Close via edd15ab
