### ISSUE TITLE
Conditional logic (among elements) doesn't work

### ISSUE THREAD

**Issue by hernansaa** [CalderaWP/cf-connected-forms#6]
I can connect different forms, but the conditional logic (AMONG THE FIELDS IN EACH FORM) wouldn't work when they are all together in the same "connected form". 

They only work if I refresh the navigator every time I go to a form that has conditional logic among its elements.

Ofcourse if I run a form  separately (without using the connected form plug in), the work perfectly fine.

I am using Caldera Forms v1.3.1 as you mentioned, and Wordpress  4.3.1. Also XAMPP for Linux 5.6.11 even though i have tried with a hosting service from elserver.com.

I hope I was clear enough.

**Comment by Shelob9** [comment]
Probably same issue as #5

**Comment by DavidCramer** [comment]
fixed
