### ISSUE TITLE
Save Form/Update Form button is not shown

### ISSUE THREAD

**Issue by riverBanjo** [CalderaWP/cf-connected-forms#76]
## Replication Steps
1. Create a connected form
2. Connect at least two forms
3. Notice there is no save form or update form button

## Debug Info

WordPress Version: 5.4.2

PHP Version: 7.3.5

MySQL Version: 8.0.16

Server Software: nginx/1.16.0

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Currently Active Theme: Twenty Twenty: 1.2

Plugins:

Caldera Forms: 1.9.2-beta2 Active
Connected Caldera Forms: 1.3.0-b-2 Active

**Note: I tested this with the beta2 plugin of Connected Forms and with the stable version of Connected Forms**

### JS

Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Object.yh [as createPortal] (react-dom.min.js?ver=16.9.0:163)
    at X (index.min.js?ver=1.9.2-beta2:1)
    at je (react-dom.min.js?ver=16.9.0:78)
    at ph (react-dom.min.js?ver=16.9.0:215)
    at lh (react-dom.min.js?ver=16.9.0:126)
    at O (react-dom.min.js?ver=16.9.0:121)
    at Sb (react-dom.min.js?ver=16.9.0:213)
    at wh (react-dom.min.js?ver=16.9.0:160)
    at fd (react-dom.min.js?ver=16.9.0:160)
    at react-dom.min.js?ver=16.9.0:163
ve @ react-dom.min.js?ver=16.9.0:103
c.callback @ react-dom.min.js?ver=16.9.0:114
yg @ react-dom.min.js?ver=16.9.0:62
xg @ react-dom.min.js?ver=16.9.0:61
Ti @ react-dom.min.js?ver=16.9.0:149
unstable_runWithPriority @ react.min.js?ver=16.9.0:26
Ma @ react-dom.min.js?ver=16.9.0:52
Ia @ react-dom.min.js?ver=16.9.0:140
Sb @ react-dom.min.js?ver=16.9.0:213
wh @ react-dom.min.js?ver=16.9.0:160
fd @ react-dom.min.js?ver=16.9.0:160
(anonymous) @ react-dom.min.js?ver=16.9.0:163
kh @ react-dom.min.js?ver=16.9.0:119
id @ react-dom.min.js?ver=16.9.0:163
render @ react-dom.min.js?ver=16.9.0:228
(anonymous) @ index.min.js?ver=1.9.2-beta2:1

react-dom.min.js?ver=16.9.0:163 Uncaught Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Object.yh [as createPortal] (react-dom.min.js?ver=16.9.0:163)
    at X (index.min.js?ver=1.9.2-beta2:1)
    at je (react-dom.min.js?ver=16.9.0:78)
    at ph (react-dom.min.js?ver=16.9.0:215)
    at lh (react-dom.min.js?ver=16.9.0:126)
    at O (react-dom.min.js?ver=16.9.0:121)
    at Sb (react-dom.min.js?ver=16.9.0:213)
    at wh (react-dom.min.js?ver=16.9.0:160)
    at fd (react-dom.min.js?ver=16.9.0:160)
    at react-dom.min.js?ver=16.9.0:163
yh @ react-dom.min.js?ver=16.9.0:163
X @ index.min.js?ver=1.9.2-beta2:1
je @ react-dom.min.js?ver=16.9.0:78
ph @ react-dom.min.js?ver=16.9.0:215
lh @ react-dom.min.js?ver=16.9.0:126
O @ react-dom.min.js?ver=16.9.0:121
Sb @ react-dom.min.js?ver=16.9.0:213
wh @ react-dom.min.js?ver=16.9.0:160
fd @ react-dom.min.js?ver=16.9.0:160
(anonymous) @ react-dom.min.js?ver=16.9.0:163
kh @ react-dom.min.js?ver=16.9.0:119
id @ react-dom.min.js?ver=16.9.0:163
render @ react-dom.min.js?ver=16.9.0:228
(anonymous) @ index.min.js?ver=1.9.2-beta2:1

The last call in the stack is to this:
![2020-07-14_16-06-02](https://user-images.githubusercontent.com/43787368/87471586-9b7f8200-c5ec-11ea-992f-fce08f485560.png)

### JS Warning

admin.php?edit=CF5f0e03412b129&page=caldera-forms:1 [DOM] Found 2 elements with non-unique id #caldera-forms-custom_callback: (More info: https://goo.gl/9p2vKq)

**Comment by New0** [comment]
This should be closed via - https://github.com/CalderaWP/Caldera-Forms/commit/97a4b0e488d8bee21c53cdf21342290bb52c3761 -
