### ISSUE TITLE
When navigating backwards, conditionals JS is outputted twice/ Conditionals don't work

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/cf-connected-forms#8]
Probably the cause of #5 and #6

**Comment by Shelob9** [comment]
BTW I tried deleting the script element with the conditionals before we reloading, which didn't help. Makes me think that the double script is only the first problem.

**Comment by Shelob9** [comment]
To reproduce, make a form with a conditional in it. Make that step 1 in the sequence and allow back navigation to it. Enter some stuff in there. Go to step 2, navigate back to it and see that conditionals are not working.

**Comment by DavidCramer** [comment]
Fixed
